### ISSUE TITLE
Project Start Checklist

### ISSUE THREAD

**Issue by okorshenko** [magento/adobe-substance-integration#1]
Please add project start checklist here

ToDo:
 - [ ] Create a spike for converting Apple format to Android  - @sivaschenko 
 - [ ] Create a spike for preview generation - @sivaschenko 
 - [ ] Create a spike to analyze which kind metadata we need to store - @sivaschenko 
 - [x] Prepare repo to be converted into public repo - @filmaj 
    - [Legal review has been filed](https://git.corp.adobe.com/OpenSourceAdvisoryBoard/opensource_submission_process/issues/660), here is what we need added:
        - [x] OSL license
        - [x] COPYING.txt
        - [x] README specifying project basics
        - [x] Magento copyright headers where appropriate
        - [x] CONTRIBUTING.md and CODE_OF_CONDUCT.md

**Comment by lenaorobei** [comment]
Mentioned TODOs are not relevant anymore. Create spike for iOS https://github.com/magento/adobe-substance-integration/issues/10
